version: 0.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/app
hooks:
  AfterInstall:
   - location: scripts/build
     timeout: 300
     runas: root
  ApplicationStart:
   - location: scripts/process_doc
     timeout: 300
     runas: root