version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/app
hooks:
  AfterInstall:
   - location: scripts/build
     timeout: 300
     runas: root
  # ApplicationStart:
  #  - location: scripts/start_server
  #    timeout: 300
  #    runas: root