name = "shaiq-resume-api"
main = "worker/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

r2_buckets = [
    { binding = "RESUME_BUCKET", bucket_name = "shaiq-resume-storage" },
]

routes = [{ pattern = "resume.shaiq.dev", custom_domain = true }]

[observability.logs]
enabled = false
