#!/bin/bash

DR_ROOT=/home/ubuntu
DR_NAME=resume
DR_TEX_SOURCE=$DR_ROOT/app/src
DR_OUT=$DR_ROOT/app/output


if [ $(dpkg-query -W -f='${Status}' uuidgen 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
  apt-get install uuidgen -y;
fi

DR_VERSION=$(echo $(uuidgen) | rev | cut -d- -f1 | rev)
sed -i -e "s/__VERSION__/$DR_VERSION/" $DR_TEX_SOURCE/$DR_NAME.tex

# Build the tex source
cd $DR_TEX_SOURCE
sudo pdflatex $DR_TEX_SOURCE/$DR_NAME.tex

# Clean Up
rm *.aux *.log *.out *.bcf *.run.xml

# Add the PDF to output
rm -rf $DR_OUT
mkdir -p $DR_OUT
mv $DR_NAME.pdf $DR_OUT/$DR_NAME-$DR_VERSION.pdf