#!/bin/bash

DR_ROOT=/home/ubuntu
DR_REGION=ap-south-1
DR_HANDLER=$DR_ROOT/app/handlers/
DR_FUNCTION=dresume

# Create the zip file
cd $DR_HANDLER
zip -r $DR_FUNCTION.zip index.js

# Deploy the function
aws lambda update-function-code --function-name $DR_FUNCTION --zip-file fileb://$DR_FUNCTION.zip --region $DR_REGION

# Remove the zip file
rm $DR_FUNCTION.zip