#!/bin/bash

DR_REGION=ap-south-1
DR_BUCKET=shaiq-resume
DR_OUT=~/app/output

# Get the generated pdf file
DR_ARTIFACT=$(ls $DR_OUT | tail -n 1)

# Upload the file to S3
aws s3 cp $DR_OUT/$DR_ARTIFACT s3://$DR_BUCKET/ --region $DR_REGION